Dmbm 742/review send special category data
co-cddo/data-marketplace pull request #55
Opened 2023-08-29 13:43 UTC by gabimartini

2023-08-29 20:33 UTC, kjoshi requested changes
Thanks Gabi,
Here are a few issues I've spotted on the Check page:

## Item titles
The name of each item doesn't match what's on the prototype. E.g.
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/5ece28e9-3f55-4357-acf7-a21c9c71dd9b)
The steps in the formdata all have names which are used on the overview pages. E.g.:
https://github.com/co-cddo/data-marketplace/blob/main/src/models/shareRequestTemplate.json#L155
It'd be good if these names could be re-used on the check page.

## Missing Not Required items
The items that are `Not Required` still need to be on the check page:
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/d699a37c-e9de-4eab-9724-4cb23a7864f5)
So I think we also need to include the `NOT REQUIRED` items in the loop and just display a _Not Required_ message.

## Large gaps
There are some quite large gaps at before quite a lot of the items. E.g.:
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/99e0b403-8153-41e6-a22f-c0cb1f5968d8)
It'd be good to try and get rid of the gaps so it looks more similar to the prototype

## Project aims
The project aims seem to be displayed twice.
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/ddc9a533-3151-414f-bc2f-43632c7a0ced)

## Date
If no date is entered it is rendered on the page as `null/null/null`. It would be better to just have `Unrequested`, like what will be shown on the [Created Requests](https://cddodatamarketplace.atlassian.net/jira/software/projects/DMBM/boards/6?selectedIssue=DMBM-733) page
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/8fc55fb1-e08b-41aa-b0e9-9b9b81041d34)

## Missing additional information
In the `Data travel outside UK` section if the answer is yes we also need to display the countries listed in the `data-travel-location` page.
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/f0a2c208-1996-44cc-afd1-962714d50a51)

The same also needs to be done in the `Other organisations accessing data` section
![image](https://github.com/co-cddo/data-marketplace/assets/1217533/990e8a32-cb48-4e8f-8797-0698e5c6c23c)

2023-08-31 17:12 UTC, AShaww commented on src/views/acquirer/check.njk
> +    <div class="govuk-grid-column-two-thirds">
can we change this to full-width

2023-08-31 17:13 UTC, AShaww commented on src/helperFunctions/checkhelper.ts
> +        controller: "Controler",
Can you take a look at this line please

2023-08-31 17:27 UTC, AShaww submitted a review, later dismissed
This is looking really good Gabi.

I've requested a few changes.

Would it be possible to also implement something like this for the `date` if null and if lawful-personal/lawful-special is not required: 

![image](https://github.com/co-cddo/data-marketplace/assets/71328022/5a4efe67-348c-440b-aee3-81adf43f079f)

Many thanks

2023-09-01 07:47 UTC, gabimartini commented
> This is looking really good Gabi.
> 
> I've requested a few changes.
> 
> Would it be possible to also implement something like this for the `date` if null and if lawful-personal/lawful-special is not required:
> 
> ![image](https://user-images.githubusercontent.com/71328022/264727436-5a4efe67-348c-440b-aee3-81adf43f079f.png)
> 
> Many thanks

Hi Amir, I've done your suggestions :) regard to this date and not required, this is requirement for the next ticket

2023-09-01 13:21 UTC, kjoshi approved these changes
All the remaining small issues were solved by #61, so this is good to go 👍

2023-09-01 13:24 UTC, kjoshi approved these changes
Small merge conflict needed sorting out. All good 👍

2023-09-01 13:25 UTC, merged