implemented declaration page - acquirer
co-cddo/data-marketplace pull request #56
Opened 2023-08-29 17:14 UTC by AShaww

Implemented the declaration page in the acquirer journey

2023-08-29 20:51 UTC, kjoshi requested changes
Thanks Amir, mostly looks good to me!

One thing to add:
Once the `Send data share request` button is pressed we also need to update the status of the form to `AWAITING REVIEW`.

Maybe the easiest thing would be to just add another check to the `POST` route. Something like:
```
if(req.body.continueButton && formStep === 'declaration') {
    formdata.status = "AWAITING REVIEW"
}
```

It might also be nice if you could update the type of the `FormData.status` property in `express.d.ts`. Maybe something like:

```
interface FormData {
  ...
  status: FormStatus;
  ...
}

type FormStatus = "IN PROGRESS" | "AWAITING REVIEW" ......etc.
```
(plus the other types shown in [DMBM-733](https://cddodatamarketplace.atlassian.net/jira/software/projects/DMBM/boards/6?selectedIssue=DMBM-733))

2023-08-30 15:29 UTC, kjoshi requested changes

2023-08-30 15:29 UTC, kjoshi commented on src/types/express.d.ts
> +  | "NOT REQUIRED"
These two are only relevant to particular steps on the form, not the form as a whole. So I think we can get rid of them.
```suggestion
```

2023-08-31 09:57 UTC, kjoshi approved these changes
Looks good thanks Amir 👍

2023-08-31 10:04 UTC, madz-lw approved these changes
LGTM 🙂

2023-08-31 10:25 UTC, merged